<meta property="og:title" content="{{ $seo['title'] }}"/>
<meta property="og:description" content="{{ $seo['description'] }}"/>
<meta property="og:image" content="{{ $seo['image'] }}"/>
<meta name="twitter:title" content="{{ $seo['title'] }}">
<meta name="twitter:description" content="{{ $seo['description'] }}">
<meta name="twitter:image:src" content="{{ $seo['image'] }}">
<meta itemprop="name" content="{{ $seo['title'] }}">
<meta itemprop="description" content="{{ $seo['description'] }}">
<meta itemprop="image" content="{{ $seo['description'] }}"> 